### ISSUE TITLE
The README lacks comprehensive documentation

### ISSUE THREAD

**Issue by adarsh-site** [Nandini80/CityPlus#10]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started.

**Comment by adarsh-site** [comment]
@Nandini80 can you please assign this issue to me.

**Comment by Nandini80** [comment]
I have already assigned this issue to you. You can start working on it.

**Comment by Nandini80** [comment]
@jinx-vi-0 Are you still working on this issue.

**Comment by adarsh-site** [comment]
> @jinx-vi-0 Are you still working on this issue.

yes, I will update it by today itself.

**Comment by Gursimranjeet-Singh** [comment]
I have already added the steps for setup .
Please look at it..

**Comment by adarsh-site** [comment]
@Nandini80 I have created a pr, please check it let me know feedback.
