### ISSUE TITLE
Issue with Form Submission: Cannot POST /Signup

### ISSUE THREAD

**Issue by Gursimranjeet-Singh** [Nandini80/CityPlus#11]
When attempting to submit the login and signup forms in the application, I encounter an error message stating "Cannot POST /Signup". This issue prevents users from successfully logging in or signing up, hindering the functionality of the application.

Instead of processing the form submission as expected, users encounter an error message indicating "Cannot POST /Signup". This suggests a breakdown in the communication between the client-side form submission and the server-side endpoint handling. There may be issues related to the client-side request format or the server's inability to handle the POST request properly.

![Web capture_18-3-2024_3240_localhost](https://github.com/Nandini80/CityPlus/assets/135559941/3daf1e10-1221-4f78-9a9c-ceaf06268d5a)
![Web capture_18-3-2024_3216_localhost](https://github.com/Nandini80/CityPlus/assets/135559941/b19cb0fb-07d2-422e-b82a-13e7513bdbf7)

**Comment by Nandini80** [comment]
Keep me updated about your progress.

**Comment by Gursimranjeet-Singh** [comment]
It seems that there's an issue with the connection between the frontend (React) and the backend (Node).Have you connected it ? Because as far I figured nodejs is not rendering frontend only handling request?

**Comment by Nandini80** [comment]
Yes, it was working before, but after some changes in Mongoose, it stopped working. If you can fix that, then it would be great.
