### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by Nandini80** [Nandini80/CityPlus#16]

**Comment by Hrithikshetty** [comment]
Can you please assign me this task  ..I'll will make sure that a good footer is created

**Comment by Nandini80** [comment]
Assigned

**Comment by Hrithikshetty** [comment]
done with the Footer. please accept the merge request...

**Comment by Nandini80** [comment]
Please mention the issue number in your PR.

**Comment by Hrithikshetty** [comment]
Okay

**Comment by alvin-dennis** [comment]
@Nandini80 if he's not working on it. May I solve that?
I have seen the pull req

**Comment by Nandini80** [comment]
ok you can work on this issue.

**Comment by alvin-dennis** [comment]
@Nandini80 is it ok if I can use his code and make the rectifications u mentioned?

**Comment by Nandini80** [comment]
yes

**Comment by alvin-dennis** [comment]
@Nandini80 Pls check the pr
