### ISSUE TITLE
CORS is not setup

### ISSUE THREAD

**Issue by Adii2202** [Nandini80/CityPlus#19]
![image](https://github.com/Nandini80/CityPlus/assets/131331573/e4783de7-a817-4664-8cef-6f409e2c9991)

Need to setup CORS

**Comment by Hrithikshetty** [comment]
assign me this

**Comment by Gursimranjeet-Singh** [comment]
@Adii2202 @Hrithikshetty  we don't need cors since server side is rendering the client side so both are on the same port

**Comment by Gursimranjeet-Singh** [comment]
@Adii2202  have you  updated your fork?

**Comment by Hrithikshetty** [comment]
hey @Gursimranjeet-Singh ...may be... but when I added cors and used fetch instead of axios both sign up and login worked perfectly for me ...

**Comment by Adii2202** [comment]
yes yess
