### ISSUE TITLE
Issue: Non Responsive UI

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/CityPlus#2]
The UI of the application is not responsive and elements come on top of each other when viewed from a smaller screen

![image](https://github.com/Nandini80/CityPlus/assets/127482713/2871ca57-832b-4f2e-a81a-81f969b3a05d)
![image](https://github.com/Nandini80/CityPlus/assets/127482713/3624b87f-c4bd-4a0f-b34b-88d0744c72f8)

**Comment by Nandini80** [comment]
I am assigning this task to you. Please make the changes accordingly and ensure responsiveness.
