### ISSUE TITLE
Issue :Lack Of Navbar at Terms And Conditions Page

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/CityPlus#3]
there is no Navbar to go back to home page from the terms and conditions page
![image](https://github.com/Nandini80/CityPlus/assets/127482713/8a8e5533-6c60-49ac-9fd1-a7f216010506)

**Comment by jiveshkalra** [comment]
Nav Bar is also missing at the signup and Login Pages

**Comment by Nandini80** [comment]
Add the navbar on these pages.
