### ISSUE TITLE
Exposed MongoDB Credentials

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/CityPlus#4]
Your MongoDB Server Credentials , Username And Password Are exposed onto github , credentials of server should preferably be in in a `.env` file and removed from github to prevent its misuse.

**Comment by Nandini80** [comment]
I have assigned you the issues you raised before. Kindly complete those first, and then I will assign this issue to you.

**Comment by jiveshkalra** [comment]
can you assign me this issue now? 
so i can start working on it

**Comment by Nandini80** [comment]
Yes firstly complete this task.

**Comment by jiveshkalra** [comment]
please assign the task to me

**Comment by jiveshkalra** [comment]
I have made the necessary changes please check
