### ISSUE TITLE
Issue: Misleading "Correct" Text on Login

### ISSUE THREAD

**Issue by jiveshkalra** [Nandini80/CityPlus#5]
The "Correct" text on the login/ Registration page should have more logic to it , as currently its only checking if it has any input and displaying correct, even if the input is not an actual email or in case of password , even if it is a weak password of 1 letter, this ideally should have some more rules to ensure a good security . 
![image](https://github.com/Nandini80/CityPlus/assets/127482713/89a8a64f-5ffa-4c49-b82d-8863fce88a87)

**Comment by Nandini80** [comment]
I have assigned you the issues you raised before. Kindly complete those first, and then I will assign this issue to you.

**Comment by jiveshkalra** [comment]
can you assign me this issue now? 
so i can start working on it

**Comment by Nandini80** [comment]
I am assigning this issue to you. You can start working on this issue.

**Comment by Nandini80** [comment]
Any update?

**Comment by jiveshkalra** [comment]
just working on it , i was out of station for few days , just by tomorrow all commits will be done.

**Comment by Nandini80** [comment]
ok.
